# @ref https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 2
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio.storage.svc.cluster.local
      accessKeyId: minio
      secretAccessKey: minio123
      s3ForcePathStyle: true
      http_config:
        insecure_skip_verify: true

#gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    limits:
      # cpu: 3
      memory: 1Gi # 4Gi
    requests:
      # cpu: 2
      memory: 500Mi # 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB

chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
  resources:
    limits:
      # cpu: 1
      memory: 200Mi
    requests:
      # cpu: 0.5
      memory: 20Mi

resultsCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB
  resources:
    limits:
      # cpu: 1
      memory: 200Mi
    requests:
      # cpu: 100m
      memory: 20Mi

# Enable minio for storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
