apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-cluster
  namespace: database
spec:
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 1h
  values:
    cluster:
      roles:
      - ensure: present
        name: infisical
        passwordSecret:
          name: cloudnative-pg-role-infisical-cred
