apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: database
spec:
  chart:
    spec:
      chart: dragonfly
      sourceRef:
        kind: HelmRepository
        name: dragonfly
      version: v1.31.0
  interval: 1h
  values:
    passwordFromSecret:
      enable: false
      existingSecret:
        key: password
        name: dragonfly-auth
    storage:
      enabled: true
