apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: database
spec:
  chart:
    spec:
      chart: dragonfly
      sourceRef:
        kind: HelmRepository
        name: dragonfly
  interval: 1h
  values:
    storage:
      enabled: true
