apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dragonfly
  namespace: database
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly
