# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
  namespace: media
spec:
  chart:
    spec:
      chart: autobrr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/autobrr
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-db:
              enabled: true
              type: init
              imageSelector: postgress-init-image
              env:
                INIT_POSTGRES_HOST: &dbHost media-pg-cluster-rw.media.svc.cluster.local
                INIT_POSTGRES_PORT: &dbPort
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: port
                    expandObjectName: false
                INIT_POSTGRES_DBNAME: &dbName autobrr
                INIT_POSTGRES_USER: &dbUser
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: username
                    expandObjectName: false
                INIT_POSTGRES_PASS: &dbPassword
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: password
                    expandObjectName: false
                INIT_POSTGRES_SUPER_PASS:
                  secretKeyRef:
                    name: media-pg-cluster-superuser
                    key: password
                    expandObjectName: false
          containers:
            main:
              env:
                AUTOBRR__BASE_URL: /autobrr
                AUTOBRR__DATABASE_TYPE: postgres
                AUTOBRR__POSTGRES_HOST: *dbHost
                AUTOBRR__POSTGRES_PORT: *dbPort
                AUTOBRR__POSTGRES_DATABASE: *dbName
                AUTOBRR__POSTGRES_USER: *dbUser
                AUTOBRR__POSTGRES_PASS: *dbPassword
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
    postgress-init-image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
      pullPolicy: IfNotPresent
