# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/bazarr
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-db:
              enabled: true
              type: init
              imageSelector: postgress-init-image
              env:
                INIT_POSTGRES_HOST: &dbHost media-pg-cluster-rw.media.svc.cluster.local
                INIT_POSTGRES_PORT: &dbPort
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: port
                    expandObjectName: false
                INIT_POSTGRES_DBNAME: &dbName bazarr
                INIT_POSTGRES_USER: &dbUser
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: username
                    expandObjectName: false
                INIT_POSTGRES_PASS: &dbPassword
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: password
                    expandObjectName: false
                INIT_POSTGRES_SUPER_PASS:
                  secretKeyRef:
                    name: media-pg-cluster-superuser
                    key: password
                    expandObjectName: false
          containers:
            main:
              env:
                BAZARR__SERVER__URLBASE: /bazarr
                POSTGRES_ENABLED: true
                POSTGRES_HOST: *dbHost
                POSTGRES_PORT: *dbPort
                POSTGRES_DATABASE: *dbName
                POSTGRES_USERNAME: *dbUser
                POSTGRES_PASSWORD: *dbPassword
              envFrom:
                - secretRef:
                    name: media-secret
                    expandObjectName: false
            exportarr:
              env:
                APIKEY:
                  secretKeyRef:
                    name: media-secret
                    key: BAZARR__AUTH__APIKEY
                    expandObjectName: false
                URL: http://bazarr:6767/bazarr
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
    metrics:
      main:
        enabled: true
    postgress-init-image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
      pullPolicy: IfNotPresent
