# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chinesesubfinder
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/premium/app-template
  values:
    image:
      repository: allanpk716/chinesesubfinder
      pullPolicy: IfNotPresent
      tag: v0.55.3
    service:
      main:
        ports:
          main:
           port: 19035
           targetPort: 19035
          media:
            port: 19037
            targetPort: 19037
    workload:
      main:
        podSpec:
          containers:
            main:
              image: image
              env:
                PERMS: false
                PGID: 568
                PUID: 568
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
                limits:
                  cpu: "4"
                  memory: 8Gi
              securityContext:
                runAsNonRoot: false
    persistence:
      config:
        enabled: true
        size: 5Gi
        storageClass: openebs-hostpath
        targetSelector:
          main:
            main:
              mountPath: /config
      media-nfs:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
