# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cross-seed
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  dependsOn:
    - name: qbittorrent
      namespace: media
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/premium/app-template
  values:
    image:
      repository: ghcr.io/cross-seed/cross-seed
      pullPolicy: IfNotPresent
      tag: 6.1.1
    service:
      main:
        ports:
          main:
           port: 2468
           targetPort: 2468
    workload:
      main:
        podSpec:
          containers:
            main:
              image: image
              args: ["daemon"]
              resources:
                requests:
                  cpu: 10m
                limits:
                  memory: 512Mi
    persistence:
      config:
        enabled: true
        type: emptyDir
      config-file:
        enabled: true
        type: secret
        objectName: cross-seed-config
        expandObjectName: false
        mountPath: /config/config.js
        subPath: config.js
        readOnly: true
        targetSelectorAll: true
      qbittorrent:
        enabled: true
        type: pvc
        mountPath: /config/qBittorrent/BT_backup
        existingClaim: qbittorrent-config
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs

    