# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  chart:
    spec:
      chart: deluge
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/deluge
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-deluge:
              enabled: true
              type: init
              imageSelector: k8s-tools-image
              command:
                - sh
                - -c
                - mkdir -p /config/openvpn/ && curl -sLo openvpn.zip
                  https://www.privateinternetaccess.com/openvpn/openvpn.zip && unzip
                  openvpn.zip -o -d /config/openvpn/
          containers:
            main:
              env:
                VPN_ENABLED: "yes"
                VPN_USER:
                  secretKeyRef:
                    name: media-secret
                    key: PIA__USERNAME
                    expandObjectName: false
                VPN_PASS:
                  secretKeyRef:
                    name: media-secret
                    key: PIA__PASSWORD
                    expandObjectName: false
                VPN_PROV: pia
                VPN_CLIENT: openvpn
                ENABLE_STARTUP_SCRIPTS: "no"
                STRICT_PORT_FORWARD: "yes"
                USERSPACE_WIREGUARD: "no"
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
        targetSelectAll: true
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
    image:
      repository: binhex/arch-delugevpn
      pullPolicy: IfNotPresent
      tag: 2.1.1-6-05
    k8s-tools-image:
      repository: kubesail/k8s-tools
      pullPolicy: IfNotPresent
      tag: v1
