# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: deluge
  namespace: media
spec:
  chart:
    spec:
      chart: deluge
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/deluge
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-config:
              enabled: true
              type: install
              imageSelector: k8s-tools-image
              command:
                - bash
                - -c
                - mkdir -p /config/openvpn/ &&
                  curl -sLo openvpn.zip https://www.privateinternetaccess.com/openvpn/openvpn.zip &&
                  unzip -o openvpn.zip -d /tmp/openvpn/ &&
                  mv /tmp/openvpn/{china.ovpn,*.crt,*.pem} /config/openvpn/
          containers:
            main:
              env:
                LAN_NETWORK: 192.168.0.0/24
                VPN_ENABLED: "yes"
                VPN_USER:
                  secretKeyRef:
                    name: media-secret
                    key: PIA__USERNAME
                    expandObjectName: false
                VPN_PASS:
                  secretKeyRef:
                    name: media-secret
                    key: PIA__PASSWORD
                    expandObjectName: false
                VPN_PROV: pia
                VPN_CLIENT: openvpn
                STRICT_PORT_FORWARD: "yes"
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
        targetSelectAll: true
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
    securityContext:
      container:
        allowPrivilegeEscalation: true
        privileged: true
        capabilities:
          add: [NET_ADMIN]
    image:
      repository: binhex/arch-delugevpn
      pullPolicy: IfNotPresent
      tag: 2.1.1-6-05
    k8s-tools-image:
      repository: kubesail/k8s-tools
      pullPolicy: IfNotPresent
      tag: v1
