# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
  namespace: media
spec:
  chart:
    spec:
      chart: jellystat
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/jellystat
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-db:
              enabled: true
              type: init
              imageSelector: postgress-init-image
              env:
                INIT_POSTGRES_HOST: &dbHost media-pg-cluster-rw.media.svc.cluster.local
                INIT_POSTGRES_PORT: &dbPort
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: port
                    expandObjectName: false
                INIT_POSTGRES_DBNAME: &dbName jellystat
                INIT_POSTGRES_USER: &dbUser
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: username
                    expandObjectName: false
                INIT_POSTGRES_PASS: &dbPassword
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: password
                    expandObjectName: false
                INIT_POSTGRES_SUPER_PASS:
                  secretKeyRef:
                    name: media-pg-cluster-superuser
                    key: password
                    expandObjectName: false
          containers:
            main:
              env:
                POSTGRES_IP: *dbHost
                POSTGRES_PORT: *dbPort
                POSTGRES_DB: *dbName
                POSTGRES_USER: *dbUser
                POSTGRES_PASSWORD: *dbPassword
    cnpg:
      main:
        enabled: false
    postgress-init-image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
      pullPolicy: IfNotPresent
