# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lingarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/premium/app-template
  values:
    image:
      repository: lingarr/lingarr
      pullPolicy: IfNotPresent
      tag: latest
    # postgress-init-image:
    #   repository: ghcr.io/onedr0p/postgres-init
    #   tag: "16"
    #   pullPolicy: IfNotPresent
    service:
      main:
        ports:
          main:
           port: 9876
           targetPort: 9876
    workload:
      main:
        podSpec:
          # initContainers:
          #   init-db:
          #     enabled: true
          #     type: init
          #     imageSelector: postgress-init-image
          #     env:
          #       INIT_POSTGRES_HOST: &dbHost media-pg-cluster-rw.media.svc.cluster.local
          #       INIT_POSTGRES_PORT: &dbPort
          #         secretKeyRef:
          #           name: media-pg-cluster-app
          #           key: port
          #           expandObjectName: false
          #       INIT_POSTGRES_DBNAME: &dbName lingarr
          #       INIT_POSTGRES_USER: &dbUser
          #         secretKeyRef:
          #           name: media-pg-cluster-app
          #           key: username
          #           expandObjectName: false
          #       INIT_POSTGRES_PASS: &dbPassword
          #         secretKeyRef:
          #           name: media-pg-cluster-app
          #           key: password
          #           expandObjectName: false
          #       INIT_POSTGRES_SUPER_PASS:
          #         secretKeyRef:
          #           name: media-pg-cluster-superuser
          #           key: password
          #           expandObjectName: false
          containers:
            main:
              imageSelector: image
              env:
                DB_CONNECTION: sqlite
                # DB_HOST: *dbHost
                # DB_PORT: *dbPort
                # DB_DATABASE: *dbName
                # DB_USERNAME: *dbUser
                # DB_PASSWORD: *dbPassword
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
                limits:
                  cpu: "4"
                  memory: 8Gi
    # persistence:
    #   config:
    #     enabled: true
    #     type: pvc
    #     size: 5Gi
    #     mountPath: /app/config
    #     storageClass: openebs-hostpath
    #   media-movies:
    #     enabled: true
    #     type: pvc
    #     mountPath: /Media/Movies
    #     subPath: Movies
    #     existingClaim: media-nfs
    #   media-shows:
    #     enabled: true
    #     type: pvc
    #     mountPath: /Media/Shows
    #     subPath: Shows
    #     existingClaim: media-nfs
