# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: media-pg-cluster
  namespace: media
spec:
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      version: 0.x
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  interval: 1h
  # @ref https://github.com/cloudnative-pg/charts/blob/main/charts/cluster
  values:
    cluster:
      instances: 1
      storage:
        storageClass: openebs-hostpath
