# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: posterr
  namespace: media
spec:
  chart:
    spec:
      chart: posterr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/posterr
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                BASEPATH: /posterr
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
