# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  chart:
    spec:
      chart: sabnzbd
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/sabnzbd
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                SABNZBD__HOST_WHITELIST_ENTRIES: nzb.o5s.lol,sabnzbd
              envFrom:
                - secretRef:
                    name: media-secret
                    expandObjectName: false
            exportarr:
              env:
                APIKEY:
                  secretKeyRef:
                    name: media-secret
                    key: SABNZBD__API_KEY
                    expandObjectName: false
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
      downloads:
        enabled: true
        type: pvc
        size: 50Gi
        mountPath: /downloads
        storageClass: openebs-hostpath
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
    metrics:
      main:
        enabled: true
