apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr4k-config
  namespace: media
data:
  INIT_POSTGRES_DBNAME: &dbName sonarr4k
  INIT_POSTGRES_HOST: &dbHost media-pg-cluster-rw.media.svc.cluster.local
  SONARR__AUTH__METHOD: External
  SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
  SONARR__LOG__DBENABLED: "False"
  SONARR__POSTGRES__HOST: *dbHost
  SONARR__POSTGRES__MAINDB: *dbName
  SONARR__SERVER__URLBASE: /sonarr4k

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr4k
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/stable/sonarr
  values:
    workload:
      main:
        podSpec:
          initContainers:
            init-db:
              enabled: true
              type: init
              imageSelector: postgress-init-image
              env:
                INIT_POSTGRES_PORT: &dbPort
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: port
                    expandObjectName: false
                INIT_POSTGRES_USER: &dbUser
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: username
                    expandObjectName: false
                INIT_POSTGRES_PASS: &dbPassword
                  secretKeyRef:
                    name: media-pg-cluster-app
                    key: password
                    expandObjectName: false
                INIT_POSTGRES_SUPER_PASS:
                  secretKeyRef:
                    name: media-pg-cluster-superuser
                    key: password
                    expandObjectName: false
              envFrom:
                - configMapRef:
                    name: sonarr4k-config
                    expandObjectName: false
          containers:
            main:
              env:
                SONARR__POSTGRES__PORT: *dbPort
                SONARR__POSTGRES__USER: *dbUser
                SONARR__POSTGRES__PASSWORD: *dbPassword
              envFrom:
                - configMapRef:
                    name: sonarr4k-config
                    expandObjectName: false
                - secretRef:
                    name: media-secret
                    expandObjectName: false
            exportarr:
              env:
                APIKEY:
                  secretKeyRef:
                    name: media-secret
                    key: SONARR4k__AUTH__APIKEY
                    expandObjectName: false
    persistence:
      config:
        size: 5Gi
        storageClass: openebs-hostpath
      media:
        enabled: true
        type: pvc
        mountPath: /Media
        existingClaim: media-nfs
    postgress-init-image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
      pullPolicy: IfNotPresent
