# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/premium/app-template
  values:
    image:
      repository: onerahmet/openai-whisper-asr-webservice
      pullPolicy: IfNotPresent
      tag: latest
    service:
      main:
        ports:
          main:
           port: 9000
           targetPort: 9000
    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: image
              env:
                ASR_ENGINE: whisperx
                ASR_MODEL: small 
              resources:
                requests:
                  cpu: 2
                  memory: 1Gi
                limits:
                  cpu: 4
                  memory: 8Gi
    persistence:
      cache:
        enabled: true
        mountPath: /.cache
        size: 5Gi
        storageClass: openebs-hostpath
