apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: garage
  namespace: storage
spec:
  interval: 24h
  url: git+https://git.deuxfleurs.fr/Deuxfleurs/garage.git@script/helm?ref=main-v1
