apiVersion: v1
data:
  rpcSecret: MzdjNDAyYTM4NTQ2NWI3NzNmNjZmYThhOWY2YTYwYzZlY2RlMWY0MjA4NDE4ZGY5NGNlZTE2YTRkYTBhZTYwNw==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: garage-0.7.1
  name: garage-rpc-secret
  namespace: storage
type: Opaque
