apiVersion: v1
data:
  rpcSecret: MjY3MWE1Y2VkNGNhNzAwOWM4OGIzNzVlNTVhYTE0NzA1NDc2MGM1NjE0NWRhNmE1NGUzNjBiZGEzODZlMThiZA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: garage-0.7.1
  name: garage-rpc-secret
  namespace: storage
type: Opaque
