apiVersion: v1
data:
  garage.toml: |-
    metadata_dir = "/mnt/meta"
    data_dir = "/mnt/data"

    db_engine = "lmdb"

    block_size = 1048576

    replication_mode = "3"

    compression_level = 1

    rpc_bind_addr = "[::]:3901"
    # rpc_secret will be populated by the init container from a k8s secret object
    rpc_secret = "__RPC_SECRET_REPLACE__"

    bootstrap_peers = []

    [kubernetes_discovery]
    namespace = "default"
    service_name = "garage"
    skip_crd = false

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.tld"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.tld"
    index = "index.html"

    [admin]
    api_bind_addr = "[::]:3903"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: Helmraiser
  name: garage-config
  namespace: storage
