apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: storage
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  values:
    minio:
      tenant:
        accessKey: minio
        key: minio123
        name: minio
        replicas: 1
        secret: minio
        storageClass: standard
