apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: storage
spec:
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: minio-operator
  interval: 1h
  values:
    tenant:
      env:
      - name: MINIO_BROWSER_REDIRECT_URL
        value: https://minio.o5s.lol
      pools:
      - servers: 1
        size: 2Gi
        volumesPerServer: 4
