apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: garage
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: garage
    app.kubernetes.io/version: v1.2.0
    helm.sh/chart: garage-0.7.1
  name: manage-crds-default-garage
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - patch
- apiGroups:
  - deuxfleurs.fr
  resources:
  - garagenodes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
