# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      version: 2024.8.4
  interval: 1h
  # @ref https://github.com/goauthentik/helm/tree/main/charts/authentik
  values:
    authentik:
      bootstrap_email: 324418+leesiongchan@users.noreply.github.com
      postgresql:
        host: file:///postgres-creds/host
        port: file:///postgres-creds/port
        name: file:///postgres-creds/dbname
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
    redis:
      enabled: true
    server:
      envFrom: &envFrom
        - secretRef:
            name: authentik-secret
      volumeMounts: &volumeMounts
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
      volumes: &volumes
        - name: postgres-creds
          secret:
            secretName: auth-pg-cluster-app
    worker:
      envFrom: *envFrom
      volumeMounts: *volumeMounts
      volumes: *volumes
