apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - auth-pg-cluster.yaml
  - authentik.yaml
  - tf.yaml
secretGenerator:
  - name: authentik-secret
    namespace: auth
    envs:
      - configs/authentik-secret.encrypted
    options:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flux-system"
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
generatorOptions:
  disableNameSuffixHash: true
