apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: terraform-auth
  namespace: flux-system
spec:
  approvePlan: auto
  interval: 5m
  path: ./apps/auth/configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  varsFrom:
    - kind: Secret
      name: authentik-secret
      varsKeys:
        - AUTHENTIK_BOOTSTRAP_TOKEN:token
  writeOutputsToSecret:
    name: terraform-auth
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
