# @ref https://github.com/external-secrets/bitwarden-sdk-server/blob/main/README.md#certificates

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-bootstrap-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-bootstrap-certs
  namespace: security
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-bitwarden-tls
  isCA: true
  secretName: bitwarden-bootstrap-certs
  subject:
    organizations:
      - external-secrets.io
  dnsNames:
    - bitwarden-sdk-server.security.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.security.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bitwarden-cert-issuer
  namespace: security
spec:
  ca:
    secretName: bitwarden-bootstrap-certs

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: security
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.security.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.security.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bitwarden-cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
  values:
    # @ref https://github.com/external-secrets/bitwarden-sdk-server/tree/main/deploy/charts/bitwarden-sdk-server
    bitwarden-sdk-server:
      enabled: true
