apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  # TODO: need to fix the dependency order so we dont need this hack
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.crds.yaml
  - amd-gpu.yaml
  - cert-manager.yaml
  - csi-driver-nfs.yaml
  - cloudnative-pg.yaml
  - external-secrets.yaml
  - metallb.yaml
  - openebs.yaml
  - reflector.yaml
