apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 33.x
  interval: 1h
  # @ref https://artifacthub.io/packages/helm/traefik/traefik
  values:
    # Allow the Gateway to expose HTTPRoute from all namespaces
    gateway:
      namespacePolicy: All
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
