apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./generated/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
