apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth
  namespace: auth
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./generated/auth
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
