apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-id
  namespace: auth
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: pocket-id
  template:
    metadata:
      labels:
        name: pocket-id
    spec:
      containers:
      - env:
        - name: CADDY_DISABLED
          value: "true"
        - name: PUBLIC_APP_URL
          value: https://pocket.o5s.lol
        - name: TRUST_PROXY
          value: "true"
        image: ghcr.io/pocket-id/pocket-id:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
        name: pocket-id
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        volumeMounts:
        - mountPath: /app/backend/data
          name: pocket-id-data
      volumes:
      - name: pocket-id-data
        persistentVolumeClaim:
          claimName: pocket-id-data
