apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: auth
spec:
  chart:
    spec:
      chart: pocket-id
      sourceRef:
        kind: HelmRepository
        name: pocket-id-helm
      version: 0.0.0
  interval: 1h
  values: {}
