apiVersion: v1
kind: Service
metadata:
  labels:
    name: pocket-id
  name: pocket-id
  namespace: auth
spec:
  ports:
  - name: http
    port: 1411
    targetPort: 1411
  selector:
    name: pocket-id
