apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-config-pvc
  namespace: auth
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
