apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-config
  namespace: auth
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-path
