# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-secret
  namespace: media
spec:
  data:
    - secretKey: PIA__USERNAME
      remoteRef:
        key: 479b6c05-7a48-4374-8c39-b234008900a1
    - secretKey: PIA__PASSWORD
      remoteRef:
        key: 54253c92-8d30-4feb-82e5-b2340089219f
    - secretKey: SABNZBD__API_KEY
      remoteRef:
        key: 905e029b-bb84-4ebd-a1e1-b22f012394a0
    - secretKey: SABNZBD__NZB_KEY
      remoteRef:
        key: 08cfbe3d-11a1-48d9-b490-b2330124a1cf
    # arr stack keys
    - secretKey: AUTOBRR__AUTH__APIKEY
      remoteRef:
        key: 14fe298e-a093-42ac-bfdb-b22f012293a4
    - secretKey: BAZARR__AUTH__APIKEY
      remoteRef:
        key: dfc6d180-d53d-4fae-a76f-b22f012184b7
    - secretKey: OMEGABRR__AUTH__APIKEY
      remoteRef:
        key: 846d095a-b73e-45d9-9ee0-b22f0122c1f5
    - secretKey: PROWLARR__AUTH__APIKEY
      remoteRef:
        key: a102c463-5673-4bd5-b6f6-b22000e8e5ea
    - secretKey: RADARR__AUTH__APIKEY
      remoteRef:
        key: f4a9a4b8-f09b-4b6f-9838-b22000c535ff
    - secretKey: RADARR4k__AUTH__APIKEY
      remoteRef:
        key: 7ffce4c1-f743-44f8-b6e0-b22f012108fc
    - secretKey: SONARR__AUTH__APIKEY
      remoteRef:
        key: 31715aa4-aa79-49e7-bd98-b22000c51a4b
    - secretKey: SONARR4k__AUTH__APIKEY
      remoteRef:
        key: 4d9f7869-7f2d-4420-9ee5-b22f012114d3
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
