apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: media-nfs
  namespace: media
spec:
  accessModes: [ReadOnlyMany, ReadWriteMany]
  capacity:
    storage: 8Ti
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: 192.168.0.200
      share: /export/stevejobs
      subDir: /Media
    volumeHandle: media-nfs.media.svc.cluster.local##/export/stevejobs
  mountOptions: [nfsvers=4.2]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-nfs
  namespace: media
spec:
  accessModes: [ReadOnlyMany, ReadWriteMany]
  resources:
    requests:
      storage: 8Ti
  storageClassName: csi-driver-nfs
  volumeName: media-nfs
