apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-frontend
  namespace: o11y
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: query-frontend
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: query-frontend
    spec:
      containers:
      - args:
        - -query-frontend.cache-results=true
        - -query-frontend.max-cache-freshness=10m
        - -query-frontend.max-total-query-length=12000h
        - -query-frontend.query-sharding-target-series-per-shard=2500
        - -query-frontend.results-cache.backend=memcached
        - -query-frontend.results-cache.memcached.addresses=dnssrvnoa+memcached-frontend.o11y.svc.cluster.local.:11211
        - -query-frontend.results-cache.memcached.max-item-size=5242880
        - -query-frontend.results-cache.memcached.timeout=500ms
        - -query-frontend.scheduler-address=query-scheduler-discovery.o11y.svc.cluster.local.:9095
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.max-connection-age=30s
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -shutdown-delay=90s
        - -target=query-frontend
        - -usage-stats.installation-mode=jsonnet
        env:
        - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
          value: "5000"
        image: grafana/mimir:2.15.1
        imagePullPolicy: IfNotPresent
        name: query-frontend
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1200Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/mimir
          name: overrides
      terminationGracePeriodSeconds: 390
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            name: query-frontend
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          name: overrides
        name: overrides
