apiVersion: apps/v1
kind: Deployment
metadata:
  name: querier
  namespace: o11y
spec:
  minReadySeconds: 10
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: querier
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        gossip_ring_member: "true"
        name: querier
    spec:
      containers:
      - args:
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+memcached-metadata.o11y.svc.cluster.local.:11211
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.sync-dir=/data/tsdb
        - -blocks-storage.bucket-store.sync-interval=15m
        - -blocks-storage.s3.bucket-name=mimir
        - -common.storage.backend=s3
        - -common.storage.s3.access-key-id=minio
        - -common.storage.s3.endpoint=http://minio.storage.svc.cluster.local:9000
        - -common.storage.s3.secret-access-key=minio123
        - -distributor.health-check-ingesters=true
        - -ingester.ring.heartbeat-timeout=10m
        - -ingester.ring.prefix=
        - -ingester.ring.replication-factor=3
        - -ingester.ring.store=memberlist
        - -mem-ballast-size-bytes=268435456
        - -memberlist.bind-port=7946
        - -memberlist.join=dns+gossip-ring.o11y.svc.cluster.local.:7946
        - -querier.frontend-client.grpc-max-send-msg-size=104857600
        - -querier.max-concurrent=8
        - -querier.max-partial-query-length=768h
        - -querier.scheduler-address=query-scheduler-discovery.o11y.svc.cluster.local.:9095
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -store-gateway.sharding-ring.heartbeat-timeout=10m
        - -store-gateway.sharding-ring.prefix=
        - -store-gateway.sharding-ring.replication-factor=3
        - -store-gateway.sharding-ring.store=memberlist
        - -target=querier
        - -usage-stats.installation-mode=jsonnet
        env:
        - name: GOMAXPROCS
          value: "5"
        - name: JAEGER_REPORTER_MAX_QUEUE_SIZE
          value: "5000"
        image: grafana/mimir:2.15.1
        imagePullPolicy: IfNotPresent
        name: querier
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc
        - containerPort: 7946
          name: gossip-ring
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          limits:
            memory: 24Gi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/mimir
          name: overrides
      terminationGracePeriodSeconds: 180
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            name: querier
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          name: overrides
        name: overrides
