apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-index-queries
  namespace: o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached-index-queries
  serviceName: memcached-index-queries
  template:
    metadata:
      labels:
        name: memcached-index-queries
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: memcached-index-queries
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - -m 64
        - -I 5m
        - -c 16384
        - -v
        image: memcached:1.6.34-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            memory: 96Mi
          requests:
            cpu: 100m
            memory: 76Mi
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.15.1
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
  updateStrategy:
    type: RollingUpdate
