apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h
  values:
    alloy-logs:
      enabled: true
    alloy-metrics:
      enabled: false
    alloy-receiver:
      alloy:
        extraPorts:
        - name: otlp-grpc
          port: 4317
          protocol: TCP
          targetPort: 4317
      enabled: false
    alloy-singleton:
      enabled: true
    applicationObservability:
      enabled: false
      receivers:
        otlp:
          grpc:
            enabled: true
    autoInstrumentation:
      enabled: false
    cluster:
      name: k8s-monitoring
    clusterEvents:
      enabled: false
    clusterMetrics:
      enabled: false
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-nginx.o11y.svc.cluster.local/api/v1/push
    - name: loki
      type: loki
      url: http://loki-gateway.o11y.svc.cluster.local/loki/api/v1/push
    - name: tempo
      type: otlp
      url: http://tempo.o11y.svc.cluster.local:4317
    nodeLogs:
      enabled: false
    podLogs:
      enabled: true
