apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: o11y
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    adminPassword: testadmin
    adminUser: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Mimir
          type: prometheus
          uid: prom
          url: http://mimir-nginx.o11y.svc.cluster.local/prometheus
        - access: proxy
          name: Loki
          type: loki
          uid: loki
          url: http://loki-gateway.o11y.svc.cluster.local
