apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: o11y
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    admin-cache:
      enabled: true
      replicas: 3
    admin_api:
      replicas: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
    alertmanager:
      persistentVolume:
        enabled: true
      replicas: 2
      resources:
        limits:
          memory: 1.4Gi
        requests:
          cpu: 1
          memory: 1Gi
      statefulSet:
        enabled: true
    chunks-cache:
      enabled: true
      replicas: 3
    compactor:
      persistentVolume:
        size: 20Gi
      resources:
        limits:
          memory: 2.1Gi
        requests:
          cpu: 1
          memory: 1.5Gi
    distributor:
      replicas: 2
      resources:
        limits:
          memory: 5.7Gi
        requests:
          cpu: 2
          memory: 4Gi
    gateway:
      replicas: 1
      resources:
        limits:
          memory: 731Mi
        requests:
          cpu: 1
          memory: 512Mi
    index-cache:
      enabled: true
      replicas: 3
    ingester:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: target
                operator: In
                values:
                - ingester
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - ingester
            topologyKey: kubernetes.io/hostname
      persistentVolume:
        size: 50Gi
      replicas: 3
      resources:
        limits:
          memory: 12Gi
        requests:
          cpu: 3.5
          memory: 8Gi
      topologySpreadConstraints: {}
      zoneAwareReplication:
        topologyKey: kubernetes.io/hostname
    metadata-cache:
      enabled: true
      replicas: 3
    mimir:
      structuredConfig:
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        common:
          storage:
            backend: s3
            s3:
              access_key_id: minio
              endpoint: minio.storage.svc.cluster.local:9000
              insecure: true
              secret_access_key: minio123
        ruler_storage:
          s3:
            bucket_name: mimir-ruler
    minio:
      enabled: false
    nginx:
      replicas: 1
      resources:
        limits:
          memory: 731Mi
        requests:
          cpu: 1
          memory: 512Mi
    overrides_exporter:
      replicas: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    querier:
      replicas: 1
      resources:
        limits:
          memory: 5.6Gi
        requests:
          cpu: 2
          memory: 4Gi
    query_frontend:
      replicas: 1
      resources:
        limits:
          memory: 2.8Gi
        requests:
          cpu: 2
          memory: 2Gi
    results-cache:
      enabled: true
      replicas: 3
    ruler:
      replicas: 1
      resources:
        limits:
          memory: 2.8Gi
        requests:
          cpu: 1
          memory: 2Gi
    store_gateway:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: target
                operator: In
                values:
                - store-gateway
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - store-gateway
            topologyKey: kubernetes.io/hostname
      persistentVolume:
        size: 10Gi
      replicas: 3
      resources:
        limits:
          memory: 2.1Gi
        requests:
          cpu: 1
          memory: 1.5Gi
      topologySpreadConstraints: {}
      zoneAwareReplication:
        topologyKey: kubernetes.io/hostname
