apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h
  values:
    alloy-logs:
      alloy:
        clustering:
          enabled: true
        mounts:
          varlog: false
      enabled: true
    alloy-metrics:
      enabled: true
    alloy-profiles:
      enabled: false
    alloy-receiver:
      alloy:
        extraPorts:
        - name: otlp-grpc
          port: 4317
          protocol: TCP
          targetPort: 4317
        - name: otlp-http
          port: 4318
          protocol: TCP
          targetPort: 4318
      enabled: true
    alloy-singleton:
      enabled: true
    applicationObservability:
      enabled: false
      receivers:
        otlp:
          grpc:
            enabled: true
    autoInstrumentation:
      enabled: false
    cluster:
      name: k8s-monitoring
    clusterEvents:
      enabled: true
    clusterMetrics:
      controlPlane:
        enabled: true
      enabled: true
      node-exporter:
        enabled: true
        extraDiscoveryRules: '{"rule": {"action": "replace", "source_labels": ["__meta_kubernetes_node_name"],
          "target_label": "nodename"}}'
      windows-exporter:
        enabled: false
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-nginx.o11y.svc.cluster.local/api/v1/push
    - name: loki
      type: loki
      url: http://loki-gateway.o11y.svc.cluster.local/loki/api/v1/push
    - logs:
        enabled: false
      metrics:
        enabled: false
      name: tempo
      traces:
        enabled: true
      type: otlp
      url: http://tempo.o11y.svc.cluster.local:4317
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
