apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: o11y
spec:
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    ingester:
      replicas: 1
