apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: o11y
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Mimir
          type: prometheus
          uid: prom
          url: http://mimir-nginx.o11y.svc.cluster.local/prometheus
        - access: proxy
          name: Loki
          type: loki
          uid: loki
          url: http://loki-gateway.o11y.svc.cluster.local
        - access: proxy
          jsonData:
            lokiSearch:
              datasourceUid: loki
            serviceMap:
              datasourceUid: prom
            tracesToLogsV2:
              datasourceUid: loki
            tracesToMetrics:
              datasourceUid: prom
          name: Tempo
          type: tempo
          uid: tempo
          url: http://tempo.o11y.svc.cluster.local:3100
    grafana.ini:
      auth.generic_oauth:
        allow_sign_up: false
        auth_url: https://auth.o5s.lol/authorize
        auto_login: true
        client_id: 35626ae4-0a0d-420a-8739-263c6c77784f
        client_secret: vD8Ev7Mh8CfULOInDcnp6hZHKjH0e3WJ
        email_attribute_name: email:primary
        enabled: true
        name: Pocket ID
        scopes: openid email profile groups
        skip_org_role_sync: true
        token_url: https://auth.o5s.lol/api/oidc/token
