apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    alloy-metrics:
      enabled: true
    cluster:
      name: k8s-monitoring
    clusterMetrics:
      enabled: true
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-distributor.o11y.svc.cluster.local:8080/api/v1/write
    - name: loki
      type: loki
      url: http://loki.o11y.svc.cluster.local:3100/loki/api/v1/push
