apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: o11y
spec:
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    tempo:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://mimir-nginx.o11y.svc.cluster.local/api/v1/push
      reportingEnabled: false
      storage:
        trace:
          backend: s3
          s3:
            access_key: minio
            bucket: tempo
            endpoint: minio.storage.svc.cluster.local
            secret_key: minio123
            tls_insecure_skip_verify: true
