apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: o11y
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    admin-cache:
      enabled: true
    admin_api:
      replicas: 1
    alertmanager:
      persistentVolume:
        enabled: true
      statefulSet:
        enabled: true
    chunks-cache:
      enabled: true
    gateway:
      replicas: 1
    index-cache:
      enabled: true
    metadata-cache:
      enabled: true
    mimir:
      structuredConfig:
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        common:
          storage:
            backend: s3
            s3:
              access_key_id: minio
              endpoint: minio.storage.svc.cluster.local
              secret_access_key: minio123
        ruler_storage:
          s3:
            bucket_name: mimir-ruler
    minio:
      enabled: false
    nginx:
      replicas: 1
    overrides_exporter:
      replicas: 1
    querier:
      replicas: 1
    query_frontend:
      replicas: 1
    results-cache:
      enabled: true
    ruler:
      replicas: 1
    store_gateway:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: target
                operator: In
                values:
                - store-gateway
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - store-gateway
            topologyKey: kubernetes.io/hostname
      topologySpreadConstraints: {}
      zoneAwareReplication:
        topologyKey: kubernetes.io/hostname
