apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: o11y
spec:
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    admin-cache:
      enabled: true
    admin_api:
      replicas: 1
    alertmanager:
      persistentVolume:
        enabled: true
      statefulSet:
        enabled: true
    chunks-cache:
      enabled: true
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 20Mi
    compactor:
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 50Mi
    distributor:
      resources:
        limits:
          memory: 300Mi
        requests:
          memory: 50Mi
    gateway:
      replicas: 1
    index-cache:
      enabled: true
    ingester:
      replicas: 1
      resources:
        limits:
          memory: 500Mi
        requests:
          memory: 80Mi
      zoneAwareReplication:
        enabled: false
    metadata-cache:
      enabled: true
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 20Mi
    mimir:
      structuredConfig:
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        blocks_storage:
          s3:
            bucket_name: mimir-blocks
        common:
          storage:
            backend: s3
            s3:
              access_key_id: minio
              endpoint: minio.storage.svc.cluster.local
              http:
                insecure_skip_verify: true
              secret_access_key: minio123
        ruler_storage:
          s3:
            bucket_name: mimir-ruler
    minio:
      enabled: false
    nginx:
      replicas: 1
    overrides_exporter:
      replicas: 1
    querier:
      replicas: 1
    query_frontend:
      replicas: 1
    results-cache:
      enabled: true
      resources:
        limits:
          memory: 200Mi
        requests:
          memory: 20Mi
    ruler:
      replicas: 1
    store_gateway:
      replicas: 1
      resources:
        limits:
          memory: 300Mi
        requests:
          memory: 50Mi
      zoneAwareReplication:
        enabled: false
