apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    alloy-logs:
      enabled: true
    alloy-metrics:
      enabled: true
    alloy-receiver:
      enabled: true
    alloy-singleton:
      enabled: true
    applicationObservability:
      enabled: true
    autoInstrumentation:
      enabled: true
    cluster:
      name: k8s-monitoring
    clusterEvents:
      enabled: true
    clusterMetrics:
      enabled: true
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-nginx.o11y.svc.cluster.local/api/v1/push
    - name: loki
      type: loki
      url: http://loki-gateway.o11y.svc.cluster.local/loki/api/v1/push
    - name: tempo
      protocol: grpc
      type: otlp
      url: http://tempo.o11y.svc.cluster.local:4317/otlp
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
