apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: o11y
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    backend:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    chunksCache:
      writebackSizeLimit: 10MB
    compactor:
      replicas: 0
    deploymentMode: SingleBinary
    distributor:
      replicas: 0
    indexGateway:
      replicas: 0
    ingester:
      replicas: 0
    loki:
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 2
      schemaConfig:
        configs:
        - from: "2024-04-01"
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v13
          store: tsdb
      storage:
        bucketNames:
          admin: loki-admin
          chunks: loki-chunks
          ruler: loki-ruler
        s3:
          accessKeyId: minio
          endpoint: minio.storage.svc.cluster.local:9000
          http_config:
            insecure_skip_verify: true
          s3forcepathstyle: false
          secretAccessKey: minio123
        type: s3
      tracing:
        enabled: true
    minio:
      enabled: false
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    read:
      replicas: 0
    singleBinary:
      extraEnv:
      - name: GOMEMLIMIT
        value: 3750MiB
      replicas: 1
      resources:
        limits:
          cpu: 3
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
    write:
      replicas: 0
