apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h
  values:
    cluster:
      name: k8s-monitoring
    destinations:
    - name: mimir
      type: prometheus
      url: http://mimir-distributor.o11y.svc.cluster.local:9095/api/v1/write
