apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: o11y
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 1h
  values:
    adminPassword: testadmin
    adminUser: admin
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Mimir
          type: prometheus
          uid: prom
          url: http://mimir-nginx.o11y.svc.cluster.local/prometheus
        - access: proxy
          name: Loki
          type: loki
          uid: loki
          url: http://loki-gateway.o11y.svc.cluster.local
        - access: proxy
          jsonData:
            lokiSearch:
              datasourceUid: loki
            serviceMap:
              datasourceUid: prom
            tracesToLogsV2:
              datasourceUid: loki
            tracesToMetrics:
              datasourceUid: prom
          name: Tempo
          type: tempo
          uid: tempo
          url: http://tempo.o11y.svc.cluster.local:3100
    extraSecretMounts:
    - defaultMode: "0440"
      mountPath: /etc/secrets/oauth
      name: oauth-secret-mount
      readOnly: true
      secretName: grafana-generic-oauth
    grafana.ini:
      auth.generic_oauth:
        allow_assign_grafana_admin: true
        allow_sign_up: true
        api_url: https://auth.harflix.lol/api/oidc/userinfo
        auth_url: https://auth.harflix.lol/authorize
        auto_login: false
        client_id: $__file{/etc/secrets/oauth/client_id}
        client_secret: $__file{/etc/secrets/oauth/client_secret}
        enabled: true
        name: Pocket ID
        role_attribute_path: contains(groups[*], 'admin') && 'GrafanaAdmin' || 'Viewer'
        scopes: openid email profile groups
        skip_org_role_sync: true
        token_url: https://auth.harflix.lol/api/oidc/token
        use_pkce: true
      server:
        domain: o11y.o5s.lol
        root_url: https://%(domain)s/
