apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: memcached-frontend
  name: memcached-frontend
  namespace: o11y
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: memcached-frontend
