apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: query-frontend
  name: query-frontend
  namespace: o11y
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: query-frontend
