apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: compactor
  name: compactor
  namespace: o11y
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: compactor
