apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    name: distributor
  name: distributor
  namespace: o11y
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: distributor
