apiVersion: v1
kind: Service
metadata:
  labels:
    name: compactor
  name: compactor
  namespace: o11y
spec:
  clusterIP: None
  ports:
  - name: compactor-http-metrics
    port: 8080
    targetPort: 8080
  - name: compactor-grpc
    port: 9095
    targetPort: 9095
  - name: compactor-gossip-ring
    port: 7946
    targetPort: 7946
  selector:
    name: compactor
