apiVersion: v1
data: {}
kind: Secret
metadata:
  name: grafana-generic-oauth
  namespace: o11y
stringData:
  client_id: 5cd3a2a4-fd53-46b0-bb7a-f5bbaa4d5814
  client_secret: vbVltlNMp0VVbiVh6QnlYPTLiumqwEbv
type: Opaque
