apiVersion: v1
kind: Service
metadata:
  labels:
    name: querier
  name: querier
  namespace: o11y
spec:
  ports:
  - name: querier-http-metrics
    port: 8080
    targetPort: 8080
  - name: querier-grpc
    port: 9095
    targetPort: 9095
  - name: querier-gossip-ring
    port: 7946
    targetPort: 7946
  selector:
    name: querier
