apiVersion: v1
kind: Service
metadata:
  labels:
    name: distributor
  name: distributor
  namespace: o11y
spec:
  clusterIP: None
  ports:
  - name: distributor-http-metrics
    port: 8080
    targetPort: 8080
  - name: distributor-grpc
    port: 9095
    targetPort: 9095
  - name: distributor-gossip-ring
    port: 7946
    targetPort: 7946
  selector:
    name: distributor
