apiVersion: v1
kind: Service
metadata:
  labels:
    name: store-gateway
  name: store-gateway
  namespace: o11y
spec:
  ports:
  - name: store-gateway-http-metrics
    port: 8080
    targetPort: 8080
  - name: store-gateway-grpc
    port: 9095
    targetPort: 9095
  - name: store-gateway-gossip-ring
    port: 7946
    targetPort: 7946
  selector:
    name: store-gateway
