apiVersion: v1
kind: Service
metadata:
  labels:
    name: memcached-metadata
  name: memcached-metadata
  namespace: o11y
spec:
  clusterIP: None
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: exporter-http-metrics
    port: 9150
    targetPort: 9150
  selector:
    name: memcached-metadata
