apiVersion: v1
kind: Service
metadata:
  labels:
    name: ingester
  name: ingester
  namespace: o11y
spec:
  ports:
  - name: ingester-http-metrics
    port: 8080
    targetPort: 8080
  - name: ingester-grpc
    port: 9095
    targetPort: 9095
  - name: ingester-gossip-ring
    port: 7946
    targetPort: 7946
  selector:
    name: ingester
