apiVersion: v1
kind: Service
metadata:
  labels:
    name: query-scheduler
  name: query-scheduler-discovery
  namespace: o11y
spec:
  clusterIP: None
  ports:
  - name: query-scheduler-http-metrics
    port: 8080
    targetPort: 8080
  - name: query-scheduler-grpc
    port: 9095
    targetPort: 9095
  publishNotReadyAddresses: true
  selector:
    name: query-scheduler
