# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: network-configs
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: network-controllers
#   interval: 1h
#   path: ./network/configs
#   prune: true
#   retryInterval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   timeout: 5m
#   wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 1h
  path: ./network/controllers
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-routes
  namespace: flux-system
spec:
  dependsOn:
    - name: network-controllers
  interval: 1h
  path: ./network/routes
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
