# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: o11y-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 1h
  path: ./o11y/controllers
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
