apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tanka-media
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 30m
  path: ./generated/media
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m
