apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  namespace: media
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: unpackerr
  template:
    metadata:
      labels:
        name: unpackerr
    spec:
      containers:
      - image: golift/unpackerr:latest
        imagePullPolicy: IfNotPresent
        name: unpackerr
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /downloads
          name: downloads
      volumes:
      - emptyDir: {}
        name: config
      - emptyDir: {}
        name: downloads
