apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingvin-share-data
  namespace: app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
