apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: security
spec:
  chart:
    spec:
      chart: infisical-standalone
      sourceRef:
        kind: HelmRepository
        name: infisical
  interval: 1h
  values:
    infisical:
      kubeSecretRef: infisical-secret
    ingress:
      enabled: false
    postgresql:
      enabled: false
    redis:
      enabled: false
