apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: infisical
  namespace: security
spec:
  hostnames:
  - vault.o5s.lol
  parentRefs:
  - name: nginx-gateway
    namespace: network
  rules:
  - backendRefs:
    - name: infisical
      port: 8080
    matches:
    - path:
        value: /
