apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb-system
spec:
  addresses:
    # - 192.168.0.2-192.168.0.253
    # - 192.168.10.0/24
    - 192.168.0.220-192.168.0.253

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal-pool
