# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: o5s-issuer
spec:
  acme:
    email: 324418+leesiongchan@users.noreply.github.com
    privateKeySecretRef:
      name: o5s-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token
              key: token
        selector:
          dnsZones:
            - "o5s.lol"
