apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: game
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: factorio
  template:
    metadata:
      annotations:
        factorio-config-hash: 707ba771e520a334eb3724ceed8e6882
      labels:
        name: factorio
    spec:
      containers:
      - image: factoriotools/factorio:2.0.47
        imagePullPolicy: IfNotPresent
        name: factorio
        ports:
        - containerPort: 27015
          name: tcp
        - containerPort: 34197
          name: udp
          protocol: UDP
        securityContext:
          runAsGroup: 845
          runAsUser: 845
        volumeMounts:
        - mountPath: /factorio/config
          name: factorio-config
      securityContext:
        fsGroup: 845
      volumes:
      - configMap:
          name: factorio-config
        name: factorio-config
