apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: game
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: factorio
  template:
    metadata:
      annotations:
        factorio-config-hash: 1d18e47eac2bb072553d1bb20a16d03e
      labels:
        name: factorio
    spec:
      containers:
      - image: factoriotools/factorio:2.0.47
        imagePullPolicy: IfNotPresent
        name: factorio
        ports:
        - containerPort: 27015
          name: tcp
        - containerPort: 34197
          name: udp
          protocol: UDP
        securityContext:
          runAsGroup: 845
          runAsUser: 845
        volumeMounts:
        - mountPath: /factorio
          name: factorio-data
        - mountPath: /tmp
          name: factorio-config
      initContainers:
      - command:
        - /bin/sh
        - -c
        - mkdir -p /factorio/config && cp /tmp/server-settings.json /factorio/config/server-settings.json
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: init-factorio
        volumeMounts:
        - mountPath: /factorio
          name: factorio-data
        - mountPath: /tmp
          name: factorio-config
      securityContext:
        fsGroup: 845
      volumes:
      - name: factorio-data
        persistentVolumeClaim:
          claimName: factorio-data
      - configMap:
          name: factorio-config
        name: factorio-config
