apiVersion: v1
kind: Service
metadata:
  labels:
    name: factorio
  name: factorio
  namespace: game
spec:
  ports:
  - name: factorio-tcp
    port: 27015
    targetPort: 27015
  - name: factorio-udp
    port: 34197
    protocol: UDP
    targetPort: 34197
  selector:
    name: factorio
