apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: factorio
  namespace: game
spec:
  chart:
    spec:
      chart: nginx-gateway-fabric
      sourceRef:
        kind: HelmRepository
        name: factorio
  interval: 1h
  values:
    image:
      tag: 2.0.47
