apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: apps
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: memos
  template:
    metadata:
      labels:
        name: memos
    spec:
      containers:
      - image: usememos/memos:latest
        imagePullPolicy: IfNotPresent
        name: memos
