apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
