apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-seed
  namespace: media
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: cross-seed
  template:
    metadata:
      labels:
        name: cross-seed
    spec:
      containers:
      - args:
        - daemon
        image: ghcr.io/cross-seed/cross-seed:6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/ping
            port: 2468
        name: cross-seed
        readinessProbe:
          httpGet:
            path: /api/ping
            port: 2468
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/xseeds
          name: config-xseeds
        - mountPath: /config/config.js
          name: xseed-config
          readOnly: true
        - mountPath: /Media/Downloads/bt
          name: media
      volumes:
      - emptyDir: {}
        name: config
      - emptyDir: {}
        name: config-xseeds
      - name: xseed-config
        secret:
          secretName: xseed-config
      - name: media
        persistentVolumeClaim:
          claimName: media-nfs
