apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xseed-config
  namespace: media
spec:
  data:
  - remoteRef:
      key: cb298359-d993-493c-b6fd-b23900c6a7ed
    secretKey: CROSS_SEED_API_KEY
  - remoteRef:
      key: a102c463-5673-4bd5-b6f6-b22000e8e5ea
    secretKey: PROWLARR_API_KEY
  - remoteRef:
      key: f4a9a4b8-f09b-4b6f-9838-b22000c535ff
    secretKey: RADARR_API_KEY
  - remoteRef:
      key: 31715aa4-aa79-49e7-bd98-b22000c51a4b
    secretKey: SONARR_API_KEY
  target:
    template:
      data:
        data: |
          const prowlarrIndices = [1, 3, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18];

          module.exports = {
              action: "inject",
              apiKey: "{{ .CROSS_SEED_API_KEY }}",
              delay: 30,
              includeEpisodes: true,
              includeNonVideos: true,
              includeSingleEpisodes: true,
              linkCategory: "xseeds",
              linkDir: "/Media/Downloads/bt/xseeds",
              linkType: "hardlink",
              qbittorrentUrl: "http://qbittorrent.media.svc.cluster.local:10095",
              radarr: [
                  "http://radarr.media.svc.cluster.local:7878/radarr?apikey={{ .RADARR_API_KEY }}",
              ],
              skipRecheck: true,
              sonarr: [
                  "http://sonarr.media.svc.cluster.local:8989/sonarr?apikey={{ .SONARR_API_KEY }}",
              ],
              torznab: prowlarrIndices.map(i => (
                  `http://prowlarr.media.svc.cluster.local:9696/prowlarr/${i}/torznab/all/api?apikey={{ .PROWLARR_API_KEY }}`
              )),
              useClientTorrents: true,
          };
        engineVersion: v2
