apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: xseed-config
  namespace: media
spec:
  data:
  - remoteRef:
      key: cb298359-d993-493c-b6fd-b23900c6a7ed
    secretKey: CROSS_SEED_API_KEY
  - remoteRef:
      key: a102c463-5673-4bd5-b6f6-b22000e8e5ea
    secretKey: PROWLARR_API_KEY
  - remoteRef:
      key: f4a9a4b8-f09b-4b6f-9838-b22000c535ff
    secretKey: RADARR_API_KEY
  - remoteRef:
      key: 31715aa4-aa79-49e7-bd98-b22000c51a4b
    secretKey: SONARR_API_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-store
  target:
    template:
      data:
        config.js: "const prowlarrIndices = [1, 3, 9, 10, 11, 12, 13, 14, 15, 16,
          17, 18];\n\nmodule.exports = {\n\taction: \"inject\",\n\tapiKey: \"{{ .CROSS_SEED_API_KEY
          }}\",\n\tdelay: 30,\n\tincludeEpisodes: true,\n\tincludeNonVideos: true,\n\tincludeSingleEpisodes:
          true,\n\tlinkCategory: \"xseeds\",\n\tlinkDirs: [\"/Media/Downloads/bt/xseeds\"],\n\tlinkType:
          \"hardlink\",\n\tqbittorrentUrl: \"http://qbittorrent.media.svc.cluster.local:10095\",\n\tradarr:
          [\n\t\t\"http://radarr.media.svc.cluster.local:7878/radarr?apikey={{ .RADARR_API_KEY
          }}\",\n\t],\n\tskipRecheck: true,\n\tsonarr: [\n\t\t\"http://sonarr.media.svc.cluster.local:8989/sonarr?apikey={{
          .SONARR_API_KEY }}\",\n\t],\n\ttorznab: prowlarrIndices.map(\n\t\t(i) =>\n\t\t\t`http://prowlarr.media.svc.cluster.local:9696/prowlarr/${i}/api?apikey={{
          .PROWLARR_API_KEY }}`,\n\t),\n\tuseClientTorrents: true,\n};\n"
      engineVersion: v2
