# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: o11y
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 2.0.0-rc.9
  interval: 1h
  # @ref https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
  values:
    cluster:
      name: "k8s-monitoring"

    #
    # Destinations
    #
    destinations:
      - name: prometheus
        type: prometheus
        url: http://prometheus-server.o11y.svc.cluster.local
      - name: loki
        type: loki
        url: http://loki.o11y.svc.cluster.local:3100
      # - name: otlpGateway
      #   type: otlp
      #   url: https://otlp.o11y.svc.cluster.local:4317/v1/traces
      #   auth:
      #     type: basic
      #     username: "my-username"
      #     password: "my-password"
      #   metrics: { enabled: true }
      #   logs:    { enabled: true }
      #   traces:  { enabled: true }

    #
    # Features
    #
    clusterMetrics:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: true
    podLogs:
      enabled: true
    # applicationObservability:
    #   enabled: true
    # autoInstrumentation:
    #   enabled: true
    # annotationAutodiscovery:
    #   enabled: true
    # prometheusOperatorObjects:
    #   enabled: true
    # profiling:
    #   enabled: true
    # integrations:
    #   enabled: true
    # selfReporting:
    #   enabled: true

    #
    # Collectors (Alloy instances)
    #
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
    alloy-logs:
      enabled: true
    # alloy-receiver:
    #   enabled: true
    # alloy-profiles:
    #   enabled: true
