# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: o11y
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  values:
    extraScrapeConfigs: |
      - job_name: 'vector'
        static_configs:
          - targets: ['vector-agent.o11y.svc.cluster.local:9090']
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
