apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: deluge
  namespace: media
spec:
  hostnames: [btd.o5s.lol]
  parentRefs:
    - name: traefik-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: deluge
          port: 8112
