apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: o11y
spec:
  hostnames: [o11y.o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: grafana
          port: 80
