apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homarr
  namespace: dashboard
spec:
  hostnames: [o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: homarr
          port: 10245
