apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homebox
  namespace: default
spec:
  hostnames: [homebox.o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: homebox
          port: 10603
