apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr
  namespace: media
spec:
  hostnames: [seer.o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: jellyseerr
          port: 10241
