apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: media
spec:
  hostnames: [flix.o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: jellyfin
          port: 8096
