apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio
  namespace: storage
spec:
  hostnames: [minio.o5s.lol]
  parentRefs:
    - name: nginx-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: minio-console
          port: 9443
