apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sabnzbd
  namespace: media
spec:
  hostnames: [nzb.o5s.lol]
  parentRefs:
    - name: traefik-gateway
      namespace: network
  rules:
    - matches:
        - path:
            value: /
      backendRefs:
        - name: sabnzbd
          port: 10097
