apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 24h
  url: https://github.com/jellyfin/jellyfin-helm
  ref:
    tag: 1.3.x

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  chart:
    spec:
      chart: charts/jellyfin
      interval: 12h
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: jellyfin
        namespace: jellyfin
  interval: 1h
  # @ref https://github.com/jellyfin/jellyfin-helm/tree/master/charts/jellyfin
