# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
  namespace: network
spec:
  chart:
    spec:
      chart: blocky
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  interval: 1h
  # @ref https://github.com/truecharts/public/blob/master/charts/library/common
  # @ref https://github.com/truecharts/public/tree/master/charts/premium/blocky
  values:
    customDNS:
      mapping:
        - domain: o5s.lol
          dnsserver: 192.168.0.240
    service:
      dns:
        type: LoadBalancer
