# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 33.x
  interval: 1h
  # @ref https://github.com/traefik/traefik-helm-chart/tree/master
  values:
    gateway:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: o5s-issuer
      listeners:
        websecure-root:
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: o5s-lol-ca
          hostname: o5s.lol
          mode: Terminate
          namespacePolicy: All
        websecure:
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: o5s-lol-ca
          hostname: "*.o5s.lol"
          mode: Terminate
          namespacePolicy: All
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: [websecure]
        matchRule: Host(`lb.o5s.lol`)
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        http3:
          enabled: true
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    tlsStore:
      default:
        defaultCertificate:
          secretName: o5s-lol-ca
